name: Pytest Dataset Tests

on:
  push:
    branches:
      - dvc
  pull_request:
    branches:
      - dvc

jobs:
  test-dataset:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision pytest

      - name: Run pytest
        run: pytest tests/data_test.py